# Generated by Django 4.1.7 on 2023-03-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property_area_property_description_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_1',
            field=models.ImageField(default='', upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_2',
            field=models.ImageField(default='', upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_3',
            field=models.ImageField(default='', upload_to='properties/'),
        ),
    ]
