# Generated by Django 4.1.7 on 2023-03-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_property_image_1_property_image_2_property_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(default='', max_length=200),
        ),
    ]
