# Generated by Django 4.1.7 on 2023-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_property_city_property_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
