# Generated by Django 4.1.7 on 2023-03-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_property_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('instagram', models.CharField(max_length=25)),
                ('facebook', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
