# Generated by Django 4.1.7 on 2023-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='image',
            field=models.ImageField(default='', upload_to='agents/'),
        ),
    ]
