# Generated by Django 4.1.7 on 2023-03-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_agentprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='mobile',
        ),
    ]
